### ISSUE TITLE
Reduce resources usage while running the command

### ISSUE THREAD

**Issue by tuyennn** [elgentos/magento2-link-guest-orders-to-customer#7]
While running `elgentos:link-guest-orders`
- Customer email or id could be joined to order collection to avoid loading inside foreach.
- There's more where using foreach as we could change to iterator instead to reduce resources usage

**Comment by peterjaap** [comment]
I’d welcome a PR! I whipped this up in 15 mins so there’s definitely a lot of improvement opportunity.
